# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea52c6daa25bc59273750aaedc6f02bd4ee48f6abf27523401e191f04c94325ad36bf0daa3082b6b2ced36415156298d192af88b70d23e566231fff21962c6a

test:
  secret_key_base: 91c6e99b3bed77dc738730368f5b7c83526450dd83fcee08e8527a9a20b7bff3530342ebf0d9c22db701f00b949e7dcb2f98b5fb85a4a4b0cd75a90f7419db5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
